server:
  port: ${PORT:8080}

spring:
  application:
    name: time-management-app
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql

  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
